spring.application.name=backend
groq.api.key=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
google.search.api.key=AIzaSyCEesM48QNetFCI-lTzctbHYLx2cUGxzwM
google.search.engine.id=71e7127398c1449b2
